// Clinical Terms Detection Library for Echocardiogram Qualification

export interface ClinicalTerm {
  category: string;
  term: string;
  variations: string[];
  weight: number; // Higher weight = more likely to qualify
}

export const CARDIAC_SYMPTOMS: ClinicalTerm[] = [
  {
    category: "Cardiac Symptoms",
    term: "Chest Pain",
    variations: [
      "chest pain",
      "chest discomfort",
      "chest pressure",
      "chest tightness",
      "angina",
      "substernal chest pain",
      "precordial pain",
      "retrosternal discomfort",
    ],
    weight: 9,
  },
  {
    category: "Cardiac Symptoms",
    term: "Dyspnea",
    variations: [
      "dyspnea",
      "shortness of breath",
      "sob",
      "difficulty breathing",
      "breathlessness",
      "respiratory distress",
      "labored breathing",
      "air hunger",
    ],
    weight: 9,
  },
  {
    category: "Cardiac Symptoms",
    term: "Palpitations",
    variations: [
      "palpitations",
      "heart racing",
      "irregular heartbeat",
      "arrhythmia",
      "heart fluttering",
      "skipped beats",
      "racing heart",
      "pounding heart",
    ],
    weight: 8,
  },
  {
    category: "Cardiac Symptoms",
    term: "Syncope",
    variations: [
      "syncope",
      "presyncope",
      "near syncope",
      "fainting",
      "lightheadedness",
      "dizziness",
      "loss of consciousness",
      "passed out",
      "blacked out",
      "near-fainting",
    ],
    weight: 9,
  },
  {
    category: "Cardiac Symptoms",
    term: "Orthopnea",
    variations: [
      "orthopnea",
      "paroxysmal nocturnal dyspnea",
      "pnd",
      "cannot lie flat",
      "uses pillows to sleep",
      "nocturnal dyspnea",
      "wakes up short of breath",
    ],
    weight: 8,
  },
  {
    category: "Cardiac Symptoms",
    term: "Edema",
    variations: [
      "edema",
      "peripheral edema",
      "lower extremity edema",
      "bilateral leg swelling",
      "ankle swelling",
      "pedal edema",
      "pitting edema",
      "leg swelling",
      "feet swelling",
      "dependent edema",
    ],
    weight: 7,
  },
  {
    category: "Cardiac Symptoms",
    term: "Exercise Intolerance",
    variations: [
      "fatigue",
      "exercise intolerance",
      "decreased exercise tolerance",
      "exertional symptoms",
      "exertional dyspnea",
      "reduced functional capacity",
      "unable to exercise",
      "gets tired easily",
      "exertional fatigue",
    ],
    weight: 6,
  },
];

export const CARDIAC_HISTORY: ClinicalTerm[] = [
  {
    category: "Cardiac History",
    term: "Myocardial Infarction",
    variations: [
      "myocardial infarction",
      "mi",
      "heart attack",
      "acute coronary syndrome",
      "acs",
      "stemi",
      "nstemi",
      "anterior mi",
      "inferior mi",
      "lateral mi",
    ],
    weight: 10,
  },
  {
    category: "Cardiac History",
    term: "Heart Failure",
    variations: [
      "congestive heart failure",
      "chf",
      "heart failure",
      "hfref",
      "hfpef",
      "systolic heart failure",
      "diastolic heart failure",
      "cardiac failure",
      "decompensated heart failure",
      "acute heart failure",
    ],
    weight: 10,
  },
  {
    category: "Cardiac History",
    term: "Atrial Fibrillation",
    variations: [
      "atrial fibrillation",
      "afib",
      "a-fib",
      "atrial flutter",
      "aflutter",
      "af",
      "paroxysmal afib",
      "persistent afib",
      "permanent afib",
    ],
    weight: 9,
  },
  {
    category: "Cardiac History",
    term: "Valvular Disease",
    variations: [
      "valvular disease",
      "valve disorder",
      "mitral regurgitation",
      "aortic stenosis",
      "mitral stenosis",
      "tricuspid regurgitation",
      "aortic regurgitation",
      "mr",
      "as",
      "ms",
      "tr",
      "ar",
      "valve disease",
      "valvulopathy",
      "mitral valve prolapse",
      "mvp",
    ],
    weight: 10,
  },
  {
    category: "Cardiac History",
    term: "Cardiomyopathy",
    variations: [
      "cardiomyopathy",
      "dilated cardiomyopathy",
      "hypertrophic cardiomyopathy",
      "restrictive cardiomyopathy",
      "dcm",
      "hcm",
      "rcm",
      "ischemic cardiomyopathy",
      "non-ischemic cardiomyopathy",
    ],
    weight: 10,
  },
  {
    category: "Cardiac History",
    term: "Coronary Artery Disease",
    variations: [
      "coronary artery disease",
      "cad",
      "coronary disease",
      "ischemic heart disease",
      "ihd",
      "coronary atherosclerosis",
      "known cad",
      "history of cad",
    ],
    weight: 9,
  },
  {
    category: "Cardiac History",
    term: "Prior Cardiac Surgery",
    variations: [
      "prior cardiac surgery",
      "valve replacement",
      "cabg",
      "coronary artery bypass",
      "bypass surgery",
      "avr",
      "mvr",
      "tavr",
      "cardiac surgery",
      "heart surgery",
      "open heart surgery",
    ],
    weight: 10,
  },
  {
    category: "Cardiac History",
    term: "Murmur",
    variations: [
      "murmur",
      "systolic murmur",
      "diastolic murmur",
      "new murmur",
      "cardiac murmur",
      "heart murmur",
      "holosystolic murmur",
      "early systolic murmur",
      "late systolic murmur",
      "grade murmur",
    ],
    weight: 8,
  },
];

export const CARDIAC_FINDINGS: ClinicalTerm[] = [
  {
    category: "Cardiac Findings",
    term: "Abnormal EKG",
    variations: [
      "abnormal ekg",
      "ecg abnormality",
      "st changes",
      "t wave inversion",
      "q waves",
      "st elevation",
      "st depression",
      "abnormal ecg",
      "ekg changes",
      "ecg changes",
      "st-t changes",
      "t wave abnormality",
    ],
    weight: 8,
  },
  {
    category: "Cardiac Findings",
    term: "Elevated Cardiac Biomarkers",
    variations: [
      "elevated troponin",
      "elevated bnp",
      "elevated nt-probnp",
      "troponin positive",
      "positive troponin",
      "high bnp",
      "elevated cardiac enzymes",
      "troponin leak",
      "troponin elevation",
    ],
    weight: 10,
  },
  {
    category: "Cardiac Findings",
    term: "Cardiomegaly",
    variations: [
      "cardiomegaly",
      "enlarged heart",
      "cardiac enlargement",
      "increased cardiac silhouette",
      "heart enlargement",
    ],
    weight: 8,
  },
  {
    category: "Cardiac Findings",
    term: "JVD",
    variations: [
      "jvd",
      "jugular venous distension",
      "jugular venous distention",
      "elevated jvp",
      "jugular venous pressure elevated",
      "distended neck veins",
    ],
    weight: 7,
  },
  {
    category: "Cardiac Findings",
    term: "Gallop",
    variations: [
      "s3 gallop",
      "s4 gallop",
      "s3",
      "s4",
      "third heart sound",
      "fourth heart sound",
      "gallop rhythm",
    ],
    weight: 8,
  },
  {
    category: "Cardiac Findings",
    term: "Pulmonary Congestion",
    variations: [
      "rales",
      "crackles",
      "pulmonary edema",
      "pulmonary congestion",
      "bilateral rales",
      "lung crackles",
      "wet lungs",
    ],
    weight: 7,
  },
];

export const RISK_FACTORS: ClinicalTerm[] = [
  {
    category: "Risk Factors",
    term: "Hypertension",
    variations: [
      "hypertension",
      "htn",
      "high blood pressure",
      "elevated blood pressure",
      "bp elevated",
      "hbp",
    ],
    weight: 3,
  },
  {
    category: "Risk Factors",
    term: "Diabetes",
    variations: [
      "diabetes mellitus",
      "dm",
      "diabetes",
      "type 2 diabetes",
      "type 1 diabetes",
      "t2dm",
      "t1dm",
      "diabetic",
      "dm2",
      "iddm",
      "niddm",
    ],
    weight: 3,
  },
  {
    category: "Risk Factors",
    term: "Hyperlipidemia",
    variations: [
      "hyperlipidemia",
      "high cholesterol",
      "hypercholesterolemia",
      "dyslipidemia",
      "elevated lipids",
      "hld",
    ],
    weight: 2,
  },
  {
    category: "Risk Factors",
    term: "Family History",
    variations: [
      "family history of cardiac disease",
      "premature cad",
      "family history of heart disease",
      "fh of cad",
      "family history of mi",
      "fhx cardiac",
    ],
    weight: 3,
  },
  {
    category: "Risk Factors",
    term: "Smoking",
    variations: [
      "smoking history",
      "tobacco use",
      "smoker",
      "current smoker",
      "former smoker",
      "pack year",
      "cigarette use",
      "tobacco abuse",
    ],
    weight: 2,
  },
];

export const ALL_CLINICAL_TERMS: ClinicalTerm[] = [
  ...CARDIAC_SYMPTOMS,
  ...CARDIAC_HISTORY,
  ...CARDIAC_FINDINGS,
  ...RISK_FACTORS,
];

// Negation patterns to detect when a finding is being denied
export const NEGATION_PATTERNS: string[] = [
  "no ",
  "denies ",
  "denied ",
  "negative for ",
  "without ",
  "absence of ",
  "not present",
  "not found",
  "ruled out",
  "no evidence of",
  "no signs of",
  "no symptoms of",
  "patient denies",
  "no history of",
  "never had",
  "does not have",
  "doesn't have",
];

// Presence patterns to detect when a finding is confirmed
export const PRESENCE_PATTERNS: string[] = [
  "positive for ",
  "presents with ",
  "presenting with ",
  "complains of ",
  "reports ",
  "history of ",
  "diagnosed with ",
  "known ",
  "has ",
  "with ",
  "shows ",
  "demonstrates ",
  "reveals ",
  "consistent with ",
  "suggestive of ",
  "evidence of ",
  "findings of ",
  "noted ",
  "observed ",
  "found ",
];
